### ISSUE TITLE
DelayRetryDuration not working as intended

### ISSUE THREAD

**Issue by magicxor** [launchdarkly/dotnet-eventsource#37]
### Steps to reproduce:

1) run the server-side php script which will close a connection every time after it sends the data:
```php
<?php
header('Content-Type: text/event-stream');
header('Cache-Control: no-cache'); // recommended to prevent caching of event data.

/**
 * Constructs the SSE data format and flushes that data to the client.
 *
 * @param string $id Timestamp/id of this connection.
 * @param string $msg Line of text that should be transmitted.
 */
function sendMsg($id, $msg) {
  echo "id: $id" . PHP_EOL;
  echo "data: $msg" . PHP_EOL;
  echo PHP_EOL;
  ob_flush();
  flush();
}

$serverTime = time();

sendMsg($serverTime, 'server time: ' . date("h:i:s", time()));
```

2) run the console app:
```csharp
        static async Task Main(string[] args)
        {
            var config = Configuration.Builder(new Uri("http://localhost:8000/your_script.php"))
                .ConnectionTimeout(TimeSpan.FromSeconds(1))
                .DelayRetryDuration(TimeSpan.FromSeconds(3))
                .ReadTimeout(TimeSpan.FromMinutes(4))
                .Build();

            var evt = new EventSource(config);

            evt.Opened += (sender, eventArgs) => { Console.WriteLine("Opened"); };
            evt.Error += (sender, eventArgs) => { Console.WriteLine("Error"); };
            evt.CommentReceived += (sender, eventArgs) => { Console.WriteLine("CommentReceived"); };
            evt.MessageReceived += (sender, eventArgs) => { Console.WriteLine($"MessageReceived: {eventArgs.Message.Data}"); };
            evt.Closed += (sender, eventArgs) => { Console.WriteLine("Closed"); };

            try
            {
                await evt.StartAsync();
            }
            catch (Exception ex)
            {
                Console.WriteLine("Closed");
            }

            Console.ReadLine();
        }
```

3) There should be a delay = 3 seconds between reconnects, but EventSource reconnects immediately. It looks like it ignores DelayRetryDuration(...) setting.

### My workaround is to change some code:

- in ExponentialBackoffWithDecorrelation.cs:
```csharp
        public TimeSpan GetNextBackOff(TimeSpan retryDelay)
        {
            _reconnectAttempts++;
            return retryDelay;
        }
```
- in EventSource.cs:
```csharp
        public async Task StartAsync()
        {
            var cancellationToken = _pendingRequest.Token;
            while (!cancellationToken.IsCancellationRequested)
            {
                await MaybeWaitWithBackOff();
                try
                {
                    await ConnectToEventSourceAsync(cancellationToken);
                    _backOff.ResetReconnectAttemptCount();
                }
                catch (Exception e)
                {
                    _logger.ErrorFormat("Encountered an error connecting to EventSource: {0}", e, e.Message);
                    _logger.Debug("", e);
                }
            }
        }

        private async Task MaybeWaitWithBackOff()  {
            if (_backOff.GetReconnectAttemptCount() > 0 && _retryDelay > TimeSpan.FromMilliseconds(0))
            {
                TimeSpan sleepTime = _backOff.GetNextBackOff(_retryDelay);
                _logger.InfoFormat("Waiting {0} milliseconds before reconnecting...", sleepTime.TotalMilliseconds);
                BackOffDelay = sleepTime;
                await Task.Delay(sleepTime);
            }
            else {
                _backOff.IncrementReconnectAttemptCount();
            }
        }
```

(I think the main problem is calling MaybeWaitWithBackOff(); without await.)

**Comment by eli-darkly** [comment]
Hmm. Are you definitely using the latest release? The problem where `MaybeWaitWithBackOff` was being called without an `await` was fixed last month in version 3.1.2. You can see the current version of that line [here](https://github.com/launchdarkly/dotnet-eventsource/blob/master/src/LaunchDarkly.EventSource/EventSource.cs#L130).

**Comment by magicxor** [comment]
For some reason I was using the code from 4da02fb31cc4b5f73439f59ead25648576d6166c commit, but the problem persists in 3.1.5 too. If the server disconnects after every event, [_backOff.GetReconnectAttemptCount()](https://github.com/launchdarkly/dotnet-eventsource/blob/master/src/LaunchDarkly.EventSource/EventSource.cs#L154) will be always 0 (so actually there will be no delay), which may result in high CPU and network consumption.

I also noticed that if [content == null](https://github.com/launchdarkly/dotnet-eventsource/blob/16f80818c4e6cf759079f13f7b0b154cb9a72c59/src/LaunchDarkly.EventSource/EventSource.cs#L257) NullReferenceException will be thrown. I'm not sure if it's the normal flow or not, but it looks a bit suspicious.

**Comment by eli-darkly** [comment]
I think I see. If it's "after every event" then that means each connection was initially successful. It does reset the counter in that case - this was intended behavior, because we didn't want intermittent failures to cause increasingly long delays if they only happened once in a while.

I agree that this is still not quite right; if we want to avoid continuing to increase the backoff when things have been working correctly, we should probably have a time threshold, like only reset the counter if the connection has stayed good for X amount of time. Also, I think there is currently a flaw in the logic such that the backoff will not always be incremented even on failed connections. I'll look into this further.

Also, thanks for catching that null issue. I _think_ that in actual use cases that string will not be null (it ultimately comes from `StreamReader.ReadLine` which can return a null on end of stream, but I think if the connection is closed we will get an I/O error first) but that's not the kind of thing we should rely on.

**Comment by eli-darkly** [comment]
I believe both the "not increasing the delay after an immediately failed connection" issue and the NullReferenceException have been fixed in the 3.2.0 release.
